### ISSUE TITLE
Implementing a color picker custom component

### ISSUE THREAD

**Issue by toluaina** [crudlio/crudl-example-django#8]
Hello,

I'm trying to add a color picker as a custom component to categories.js.
This will be a new field named color to store the hex value of the selected color.
I am using react-color from https://casesandberg.github.io/react-color
I have added a color component that extends React.Component and included it in 
admin/fields/ColorPicker.jsx 

Here my ColorPicker.jsx 

```
import React from 'react';
import { PhotoshopPicker } from 'react-color';

class ColorPicker extends React.Component {
  state = {
    background: '#fff',
  };

  handleChangeComplete = (color, event) => {
    this.setState({ background: color.hex });
  };

  render() {
    return <PhotoshopPicker onChangeComplete={ this.handleChangeComplete } />;
  }
}
```

Question is: how do I bind the selected color's hex value to the color field in categories.js
so that is is saved and loaded and triggers a save button on color selection.

```
{
    name: 'color',
    label: 'Color',
    field: ColorPicker,
    onChange: {
        in: 'color',
        setInitialValue: (name) => '#fff',
    }
},
```

thanks

**Comment by sehmaschine** [comment]
Did you take a look at the existing fields? Eg, the button with the DateField should behave similar:
https://github.com/crudlio/crudl/blob/master/src/fields/DateField.jsx#L18
